name: hypertools
description: Hypertools Application

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  rxdart: ^0.23.1
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.7.0
  path_provider: ^1.6.11
  mailto: ^1.0.0
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  build_runner: ^1.10.7
  http: ^0.12.2
  simple_animations: ^1.3.9  
  flare_flutter: ^2.0.1  
  convex_bottom_bar: ^2.6.0
  persistent_bottom_nav_bar: ^3.1.0
  platform_device_id: ^0.1.3
  # https://pub.dev/packages/ota_update/example
  ota_update: ^2.4.1
  cached_network_image: ^2.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/font/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/main.ico"
  image_path_ios: "assets/images/main.ico"

flutter_native_splash:
  image: assets/images/splash-image.png
  color: "000f25"


  
fonts:
    - family: vazir
      fonts:
        - asset: assets/font/Vazir.ttf
    - family: vazirBold
      fonts:
        - asset: assets/font/Vazir-Bold.ttf
      
    - family: vazirMedium
      fonts:
        - asset: assets/font/Vazir-Medium.ttf
    - family: vazirLight
      fonts:
        - asset: assets/font/Vazir-Light.ttf
    - family: vazirfd
      fonts:
        - asset: assets/font/Vazir-FD-WOL.ttf
        - asset: assets/font/Vazir-Bold-FD-WOL.ttf
        - asset: assets/font/Vazir-Medium-FD-WOL.ttf
        - asset: assets/font/Vazir-Light-FD-WOL.ttf
        - asset: assets/font/Vazir-Thin-FD-WOL.ttf
